# Generated by Django 5.2.9 on 2025-12-06 23:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_bill_due_date_alter_bill_id_alter_bill_taxes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(default=datetime.date(2026, 1, 7)),
        ),
    ]
