# Generated by Django 4.2.27 on 2025-12-08 10:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_alter_bill_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(default=datetime.date(2026, 1, 8)),
        ),
    ]
