# Generated by Django 6.0 on 2025-12-09 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_bill_id_alter_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='due_date',
            field=models.DateField(default=datetime.date(2026, 1, 9)),
        ),
    ]
