# Generated by Django 6.0 on 2025-12-09 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_alter_bill_due_date'),
        ('reservation', '0005_alter_reservation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='reservation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reservation.reservation'),
        ),
    ]
